= Professionelle Softwareentwicklung: Praktische Übung 4
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:

== Vorbereitung 

Die Vorbereitungsarbeiten müssen Sie *vor der praktischen Übung* abschließen. 

Wir erwarten von Ihnen, dass Sie 

* ein Headset o. ä. bereithalten. Testen Sie Ihr Audiosetup mit anderen Kommilitonen (z. B. Ihrer Gruppe) aus. Sie können dazu zum Beispiel https://test.bigbluebutton.org/ benutzen. 
* den Aufgabentext unten gelesen und sich dazu schon Gedanken gemacht haben. 

== Ziele der Übung

In dieser Übung wollen wir testgetriebene Entwicklung (TDD) üben.

== Ablauf der Übung

. Schalten Sie *mindestens* das Mikrofon, aber besser auch die Kamera, ein 
. Am Anfang gibt es eine kurze Vorstellungsrunde 
. In der Gruppe wird kurz diskutiert, wie die Lösung angegangen werden soll, und es werden noch offene Fragen geklärt
. Es wird festgelegt, in welcher Reihenfolge die Driver-Rolle übernommen wird
. Die erste Person teilt Ihren Screen und übernimmt mithilfe von `mob` die Session
. Es wird an der Problemstellung gemeinsam nach den Regeln des Mob-Programmings gearbeitet
. Nach ca. der Hälfte der Zeit gibt es ein Feedback durch die Tutorin oder den Tutor
. Es wird weiter an der Problemstellung gearbeitet
. ca. 10 Minuten vor Ende der Session bekommen Sie Ihre Abschlussbewertung 

== Aufgabe 

Nachdem wir uns in der letzten praktischen Übung die seltsame Zählweise beim Tennis angeschaut haben, nehmen wir uns in dieser Woche die seltsame Zählweise beim Bowling vor.

Ein Bowling-Spiel besteht aus zehn sogenannten Frames. In jedem Frame hat ein:e Spieler:in zwei Versuche, die 10 Kegel (Pins) mit der Kugel abzuräumen. Werden alle 10 Kegel mit dem ersten Wurf abgeräumt, wird das ein Strike genannt. Werden alle 10 Kegel mit dem zweiten Wurf abgeräumt, wird das Spare genannt. Werden nicht alle Kegel abgeräumt, heißt das Open Frame.

Die Punkte, die für einen Frame vergeben werden, ist die Anzahl der abgeräumten Kegel zuzüglich eines Bonus für Strikes und Spares.

* Der Bonus für einen Spare ist die Anzahl der abgeräumten Kegel im ersten Wurf des nächsten Frames.
* Der Bonus für einen Strike ist die Anzahl der abgeräumten Kegel in den  nächsten zwei Würfen.

Wird im letzten (also dem zehnten) Frame ine Spare oder Strike erzielt, dürfen noch 1 bzw. 2 Würfe zusätzlich geworfen werden, um den Bonus für den 10. Frame zu bestimmen.

In folgendem Video wird die Zählweise erklärt: https://www.youtube.com/watch?v=oSUi1d5sAb0

Wir wollen testgetrieben eine Anwendung schreiben, die die Punkte berechnet. Die Anwendung besteht aus der Klasse `BowlingGame` und hat zwei Methoden `roll(int pins)` um das Ergebnis eines Wurfs einzugeben und eine Methode `int score()`, die den Punktestand ausrechnet.

== Verhaltensregeln

Wir erwarten von Ihnen einen respektvollen Umgang miteinander. Es gilt grundsätzlich bei uns der https://berlincodeofconduct.org/de/[Berlin Code of Conduct]. Die Tutor:innen haben die Aufgabe, die Einhaltung der Regeln zu überwachen und können bei Verstößen gegen den Verhaltenskodex Personen aus der praktischen Übung entfernen.   
