= Professionelle Softwareentwicklung: Praktische Übung 5
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:

== Vorbereitung 

Die Vorbereitungsarbeiten müssen Sie *vor der praktischen Übung* abschließen. 

Wir erwarten von Ihnen, dass Sie 

* ein Headset o. ä. bereithalten. Testen Sie Ihr Audiosetup mit anderen Kommilitonen (z. B. Ihrer Gruppe) aus. Sie können dazu zum Beispiel https://test.bigbluebutton.org/ benutzen. 
* den Aufgabentext unten gelesen und sich dazu schon Gedanken gemacht haben. 

== Ziele der Übung

In dieser Übung werden wir den Umgang mit dem Debugger und die systematische Fehlersuche trainieren. 

== Ablauf der Übung

. Schalten Sie *mindestens* das Mikrofon, aber besser auch die Kamera, ein 
. Am Anfang gibt es eine kurze Vorstellungsrunde 
. In der Gruppe wird kurz diskutiert, wie die Lösung angegangen werden soll, und es werden noch offene Fragen geklärt
. Es wird festgelegt, in welcher Reihenfolge die Driver-Rolle übernommen wird
. Die erste Person teilt Ihren Screen und übernimmt mithilfe von `mob` die Session
. Es wird an der Problemstellung gemeinsam nach den Regeln des Mob-Programmings gearbeitet
. Nach ca. der Hälfte der Zeit gibt es ein Feedback durch die Tutorin oder den Tutor
. Es wird weiter an der Problemstellung gearbeitet
. ca. 10 Minuten vor Ende der Session bekommen Sie Ihre Abschlussbewertung 

== Aufgabe 

Sie erhalten in der Übung von Ihrem Tutor oder ihrer Tutorin eine Auswahl von Programmen, die Fehler enthalten. 
Ihre Aufgabe ist es die Fehler zu finden, zu reproduzieren und ggf. auch zu beseitigen. 

Im Ordner `Shopping` finden Sie ein Beispiel, wie eine Debug-Aufgabe aussehen könnte. 
Das Beispiel ist eine etwas erweiterte Version des Programms aus der zweiten praktischen Übung. 

Zusätzlich wurde eine Funktion eingebaut, die für ein bestimmtes Geschäft eine Auflistung der Einkäufe nach Kategorien getrennt anzeigt. Die neue Funktion wird mit `report details <Name des Geschäfts>` aufgerufen. Leider funktioniert genau diese Stelle nicht richtig. 

Außerdem wurde die Ausgabe mithilfe des Tricks aus https://www.youtube.com/watch?v=Q0LFeb6x_64[Wochenblatt 6] so vorbereitet, 
dass es leichter ist, Tests für das Programm zu schreiben.

. Versuchen Sie, den Fehler zu reproduzieren, dazu werden Sie Ausgaben in mindestens zwei verschiedenen Kategorien für ein Geschäft benötigen.
. Schreiben Sie einen Test, der den Fehler automatisch reproduziert
. Beheben Sie das Problem und prüfen Sie, dass der Fehler nicht mehr auftritt

== Verhaltensregeln

Wir erwarten von Ihnen einen respektvollen Umgang miteinander. 
Es gilt grundsätzlich bei uns der https://berlincodeofconduct.org/de/[Berlin Code of Conduct]. Die Tutor:innen haben die Aufgabe, die Einhaltung der Regeln zu überwachen und können bei Verstößen gegen den Verhaltenskodex Personen aus der praktischen Übung entfernen.   
